### ISSUE TITLE
OAK branding materials

### ISSUE THREAD

**Issue by chrisli30** [OAK-Foundation/OAK-blockchain#1]
The issue stores all the images and files needed in this repo

![image](https://user-images.githubusercontent.com/2616844/113633512-f6955100-9621-11eb-9a56-4eb5d2288b35.png)
![image](https://user-images.githubusercontent.com/2616844/113633524-fb5a0500-9621-11eb-8add-4abe835b00d0.png)

![image](https://user-images.githubusercontent.com/2616844/113636716-e3857f80-9627-11eb-842a-dcb1e1a96689.png)

**Comment by irsal** [comment]
![oak_logo](https://user-images.githubusercontent.com/1693789/156277834-ed433b60-9e82-4267-8b4f-e30438dbec54.png)
