### ISSUE TITLE
How to deploy ink smart contract.

### ISSUE THREAD

**Issue by puneet166** [OAK-Foundation/OAK-blockchain#171]
**Question**

Hi , Please help me regarding it - How to deploy my ink smart contract over turning network parachain in polkadot url- "https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.turing.oak.tech#/settings".

**Comment by irsal** [comment]
We do not yet support smart contracts on Turing. Here is our roadmap for reference: https://docs.oak.tech/docs/product-roadmap/
