### ISSUE TITLE
Do you need any help building/fixing something?

### ISSUE THREAD

**Issue by herou** [OAK-Foundation/OAK-blockchain#312]
Substrate/rust developer here

Contributor on different Substrate/Rust repos: https://github.com/herou
1- Converted substrate all the recipes from frame v1 o v2 : https://github.com/JoshOrndorff/recipes/pull/471 (It took me 6 months)
2- Winner of one of Web3 grants and delivered it on time: https://github.com/w3f/Grant-Milestone-Delivery/pull/599

Let me know!

**Comment by chrisli30** [comment]
@herou, let’s discuss! Could you shoot me an email at chris@oak.tech with some backgroud of yours?

Once I receive your email I will close this issue. Thanks!

**Comment by herou** [comment]
@chrisli30 sent an e-mail.

**Comment by herou** [comment]
@chrisli30 You can close this issue!
