### ISSUE TITLE
Unit test of missed task queue needs a revamp

### ISSUE THREAD

**Issue by chrisli30** [OAK-Foundation/OAK-blockchain#396]
**Description**

The logic of test `missed_tasks_removes_completed_tasks` is incorrect. 

First, we haven't tested the process of a task being missed. Can we change the weight of this block to make the weight limit very low, so a task would be missed?

Second, after the task is missed, it should be added to the missed queue. At this point, we should check the contents of the missed queue.

Lastly, in our code, if the next block has weight capacity, will it take tasks from the missed queue and try to execute them? We should check if taskExecuted is present in the next block. Do you understand? The test case should not directly manipulate the missed task queue; instead, the task queue should be handled by the dev code.

**Environment**

Unit tests in dev environment.

**Comment by nnnnnnsssss** [comment]
Okay
