### ISSUE TITLE
Block 3288719 decoded incorrectly

### ISSUE THREAD

**Issue by Igorgro** [OAK-Foundation/OAK-blockchain#450]
**Description**

Block 3288719 events cannot be correctly decoded. Event 0 is wrongly decoded as 'TaskExecutionFailed' instead of 'TaskTriggered'

**Steps to Reproduce**

_Replace the example steps below with actual steps to reproduce the bug you're reporting._

1. Go to Polkadot.js apps
2. Try to query block 3288719 https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.turing.oak.tech#/explorer/query/3288719
3. See events decode error

**Expected vs. Actual Behavior**

Events decoded without errors

**Environment**

--

**Logs, Errors or Screenshots**

See https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.turing.oak.tech#/explorer/query/3288719

**Additional Information**

Subscan has a correct version of this block https://turing.subscan.io/block/3288719?tab=event

**Comment by chrisli30** [comment]
@Igorgro thanks for your reporting! We’ll take a look at this issue.

Out of curiosity, how did you find about this issue? For example, did you see it from Turing node logs?

**Comment by Igorgro** [comment]
I was just saving all the blocks from node and found that this one decoded incorrectly. Previously (around 6 months ago) it was ok

**Comment by chrisli30** [comment]
Gotcha, this is related to new Enum type we added in ver 2.0.0 or 2.0.1. In order to solve this we need to either update polkadot.js library, extend it with @oak-network/types, or revert to polkadot.js compatible enums.

**Comment by Igorgro** [comment]
This is still actual

**Comment by chrisli30** [comment]
Hi @Igorgro,the "Failed to decode block" error message seems to disappear after Turing runtime 296 upgrade.

```
Logs, Errors or Screenshots

See https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.turing.oak.tech#/explorer/query/3288719
```

Please check it out and let us know if that is addressed.
