### ISSUE TITLE
Problem in RPC Port configuration

### ISSUE THREAD

**Issue by SimonKraus** [OAK-Foundation/OAK-blockchain#485]
## In the latest client version v2.1.0 there is a problem in RPC port configuration.

The embedded relaychain always claims port number 9944 - even if you configure a different port for it.
Port 9944 should be available for the parachain as it has ever been.  
Instead the parachain is spawning on random ports like 36261 where the RPC is not accessible from the localhost.
The RPC returned the following error while trying to query:
`Provided Host header is not whitelisted.`

## Steps to Reproduce
Start the node client in a minimal setup like the following command to reproduce the issue:

`/path/to/oak-collator --collator --chain turing --rpc-port 9944 -- --rpc-port 9945`

You will notice that the port configured for the parachain will be assigned to the embedded relaychain instead.

- Operating system: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-89-generic x86_64)
- Template version/tag: oak-collator 2.1.0-f38b3cd002f

**Comment by chrisli30** [comment]
Thanks for the report @SimonKraus. Let us investigate this and find a resolution promptly.
