### ISSUE TITLE
The encoded hash in TaskTriggered does not contain the correct payload for XCM tasks

### ISSUE THREAD

**Issue by chrisli30** [OAK-Foundation/OAK-blockchain#505]
**Steps to Reproduce**
Take the task `4353492-0-1` on Turing Network as an example.

Run the below query in Insights,
```
SELECT block_height, id, timestamp, module, method, docs, data, extrinsic_id
FROM turing.events 
where data::text LIKE '%67gFKvqXtE5bx1E98uV6yhR9wosktNQQZyf5HdncHzvCqbUB%' AND module NOT IN ('balances','parachainStaking')
order BY block_height DESC;
```
You will see the TaskTriggered event, which contains the encodedCall
```
{'who': '67gFKvqXtE5bx1E98uV6yhR9wosktNQQZyf5HdncHzvCqbUB', 'taskId': '4353492-0-1', 'condition': {'type': 'time', 'timestamp': '1706074800'}, 'encodedCall': '0x1f00c60e71bd0f2e6d8832fea1a2d56091c48493c78801006808338e4789af9cef672b34662a6f74d0486439e4612aa5f4aa8b057f283a81c6de8aaf72cd471300008a5d78456301'}
```

**Expected vs. Actual Behavior**

The encodedCall `0x1f00c60e71bd0f2e6d8832fea1a2d56091c48493c78801006808338e4789af9cef672b34662a6f74d0486439e4612aa5f4aa8b057f283a81c6de8aaf72cd471300008a5d78456301` is not a hash that can be decoded by Turing. It is not the direct payload of the Turing task. Instead, it is the **XCM payload of task payload**. In this case, it is a hash on Moonriver, https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmoonriver.api.onfinality.io%2Fpublic-ws#/extrinsics/decode

We expect the direct payload of the task in encodedCall,  one that can be decoded by Turing. Inside that payload, it contains the information of XCM, indicating the destination of the message. That’s how we will know that the XCM payload is for Moonriver, and then we can use Moonriver adapter to decode the inner encodedCall.

**Comment by chrisli30** [comment]
@v9n, we do still need this function, right?

**Comment by chrisli30** [comment]
The XCM messsage hash will be in the XcmQueue event next to the TaskTriggered, and I think it will be hard to get it in TaskTriggered, because at the time of firing our code has not run into the message generation logic yet.

**Comment by imstar15** [comment]
After discussing with Chris, the decision is to modify the value of `encodedCall` as follows:

1. Use the call parameter of scheduleDynamicDispatch as `encodedCall`.
2. Use the entire extrinsic of scheduleXcmpTask as `encodedCall`.
