### ISSUE TITLE
Commit hash?

### ISSUE THREAD

**Issue by alexlionel** [OAK-Foundation/OAK-blockchain#516]
**Question**

_Please include information such as the following: is your question to clarify an existing resource
or are you asking about something new? what are you trying to accomplish? where have you looked for
answers?_
What is the first commit hash that was ever made in the main oak GitHub repo?

**Comment by Lalsha40** [comment]
I need solution pr no

**Comment by chrisli30** [comment]
This issue has been closed due to lack of clarity. Feel free to reopen it with more information if needed. Thank you.

**Comment by Lalsha40** [comment]
I am completely chalenge in easyA but received token only 100 vet
